### ISSUE TITLE
ASDF file download fails when downloading a dataset

### ISSUE THREAD

**Issue by JimArnow-nso** [DKISTDC/dkist#117]
Attempting to download a dataset successfully downloads the FITS frames, but the ASDF file fails to download. The Globus event log includes an error similar to:

`"550-GlobusError: v=1 c=PATH_NOT_FOUND%0D%0A550-GridFTP-Path: \"/data/87dfaf/AWVLB/87dfaf/AWVLB/VBI_L1_20531113T145215_AWVLB.asdf\"%0D%0A550-globus_gridftp_server_s3_base: S3 Error accessing \"/data/87dfaf/AWVLB/87dfaf/AWVLB/VBI_L1_20531113T145215_AWVLB.asdf\": HttpErrorNotFound: HttpErrorNotFound: %0D%0A550 End.%0D%0A",
`

I believe the issue is that the values for `base_path` and `self.meta['asdfObjectKey']` both include the proposalId and datasetId at this point:

https://github.com/DKISTDC/dkist/blob/4ec087b42caad1f09af02291ce858a8248a65aa9/dkist/dataset/dataset.py#L211

**Comment by Cadair** [comment]
Fixed by #118
