### ISSUE TITLE
Link the header table to the files / FileManager

### ISSUE THREAD

**Issue by Cadair** [DKISTDC/dkist#134]
When you slice the Dataset, it should (automatically?) be possible to view the subset of the headers table.
It should also be possible to look in the headers table and work out what index of the FileManager a row corresponds to etc

**Comment by SolarDrew** [comment]
Use a combination of [multi_ravel_index](https://numpy.org/doc/stable/reference/generated/numpy.ravel_multi_index.html) and [this trick](https://stackoverflow.com/questions/64097025/how-to-convert-n-d-slice-to-indexes-in-numpy/64097626#64097626) to return the appropriate indices.
