### ISSUE TITLE
Add test data (and a script to generate it) for TiledDataset

### ISSUE THREAD

**Issue by Cadair** [DKISTDC/dkist#154]
Mainly for asdf testing.

**Comment by Cadair** [comment]
Also assert the correct tags are used.

**Comment by SolarDrew** [comment]
Can add a test-time dep on simulator and use that for this (also to spoof larger datasets for testing #271 )

**Comment by Cadair** [comment]
I think the original scope of this issue has actually been fixed (https://github.com/DKISTDC/dkist/blob/main/dkist/data/test/test_tiled_dataset-1.0.0_dataset-1.0.0.asdf)
