### ISSUE TITLE
WCSes using a 2D Lookup table for pointing do not support inverse transform

### ISSUE THREAD

**Issue by Cadair** [DKISTDC/dkist#168]
When constructing a `VaryingCelestialTransform2D` model we [currently use `Tabular2D`](https://bitbucket.org/dkistdc/dkist-inventory/src/359e6b0c9f28586d821874b4ecc60d4449e2633d/dkist_inventory/transforms.py#lines-192:194) which does not support an inverse transform even when it's all singularly valued.

The approach to fixing this is probably to make a subclass of `Tabular2D` which does return an inverse when all the points in the table are singularly valued. This probably should be upstreamed to Astropy or else we will have to maintain it forever.

See also DCS-2680

**Comment by SolarDrew** [comment]
https://github.com/astropy/astropy/blob/main/astropy/modeling/tabular.py#L259
