### ISSUE TITLE
Default task label not always valid

### ISSUE THREAD

**Issue by SolarDrew** [DKISTDC/dkist#195]
### Description

When trying to download files with `Dataset.files.download()`, the default label generated can include invalid characters, which kills the download.

### Expected vs Actual behavior

Files should download.

Globus returns 400 Bad Request

```
    307     return GlobusHTTPResponse(r, self)
    309 log.debug(f"request completed with (error) response code: {r.status_code}")
--> 310 raise self.error_class(r)

TransferAPIError: ('POST', 'https://transfer.api.globus.org/v0.10/transfer', 'Bearer', 400, 'BadRequest', 'Invalid label characters', '7LTloJabe')
```
### Steps to Reproduce

```python
ds.files.download()
```

**Comment by Cadair** [comment]
@eigenbrot you broke it :stuck_out_tongue:

**Comment by eigenbrot** [comment]
I'll take a look. @SolarDrew, did you find this failure for all `Dataset` objects? Or is there some datasetID in particular that failed?

**Comment by SolarDrew** [comment]
It was `ALZZA`. I haven't tested with other datasets but I'll do that this afternoon.
