### ISSUE TITLE
`from astropy.coordinates import SkyCoord` sometimes breaks on Mac and Linux.

### ISSUE THREAD

**Issue by SolarDrew** [DKISTDC/dkist#250]
Think this may have been an issue with astropy 5.1. Problem occurred on both Mac and Linux. Merits further investigation.

**Comment by Cadair** [comment]
Do we have a traceback or anything for this, because this issue as it is, is pretty useless lol

**Comment by Cadair** [comment]
If you can't reproduce it then close this :wink:

**Comment by SolarDrew** [comment]
Yep, works fine on my machine :shrug: May have been 5.1 with older versions of python, but if it comes up again we can reopen this.
