### ISSUE TITLE
`TiledDataset` should be recognisable via Fido

### ISSUE THREAD

**Issue by SolarDrew** [DKISTDC/dkist#253]
### Description

There is currently no way to search for or recognise a `TiledDataset` through the Fido interface. The inventory metadata showing that a dataset is tiled should be exposed to Fido.

**Comment by Cadair** [comment]
> The inventory metadata showing that a dataset is tiled should be exposed to Fido.

If this exists, then it should be exposed already? If this is something that needs to be added to inventory then this needs to be opened data center side.

**Comment by SolarDrew** [comment]
Understood. Not sure whether it's actually in the inventory from my hastily scribbled note during the workshop. Will investigate further.

**Comment by Cadair** [comment]
This has been reported as a dataset inventory issue [at the Data Center](https://nso.atlassian.net/browse/DCS-3605).
