### ISSUE TITLE
dataset pytest cli breaks dkist-inventory package

### ISSUE THREAD

**Issue by Cadair** [DKISTDC/dkist#469]
https://bitbucket.org/dkistdc/dkist-inventory/pipelines/results/492

I think dkist-inventory imports the conftest.py from dkist and then it all goes wrong.

dkist-inventory has been pinned to dkist<1.9.0 but we clearly need a better solution to this problem.

**Comment by SolarDrew** [comment]
[Fixed in dkist-inventory.](https://bitbucket.org/dkistdc/dkist-inventory/pull-requests/55/overview)
